<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Adds a table called  language to keep track of languages for each course
 */
class Version20130618203040 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // Adds a table cal
        $sql ="
            CREATE TABLE IF NOT EXISTS languages(
                 id INT NOT NULL AUTO_INCREMENT ,
                 name VARCHAR(255),
                 PRIMARY KEY (id))
                 ENGINE = InnoDB;";
        $this->addSql($sql);

        $this->addSql("ALTER TABLE courses ADD COLUMN language_id int");
        $this->addSql("ALTER TABLE courses
                       ADD CONSTRAINT courses_languages
                       FOREIGN KEY (language_id)
                       REFERENCES languages(id)
                     ");
        $this->addSql("INSERT INTO languages VALUES ('English','French','Spanish','Italian','Chinese','German')");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
