<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Migration to add some fields to news table
 */
class Version20130622184933 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // Added description
        $this->addSql("ALTER TABLE news ADD COLUMN description text");

        // Field to store local image url
        $this->addSql("ALTER TABLE news ADD COLUMN local_image_url text");

        // Field to store remote image url
        $this->addSql("ALTER TABLE news ADD COLUMN remote_image_url text");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
