<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Migration to move initiative from a Offering level to Course level
 */
class Version20130121022923 extends AbstractMigration
{
    public function up(Schema $schema)
    {
                                      
        // Create a fake initative
        $this->addSql("INSERT INTO initiatives(id, name,code) VALUES (100,'Dummy Initiative','DUMMY')");
        // Update the schema
        $this->addSql( "ALTER TABLE courses ADD COLUMN initiative_id INT(11) DEFAULT NULL");
        $this->addSql( "UPDATE courses SET initiative_id = 100");
                                      
        // Add a table to keep track of custom data migrations                
        $this->addSql("CREATE  TABLE IF NOT EXISTS `datamigrations` (
                      `id` INT NOT NULL AUTO_INCREMENT ,
                      `version` INT NOT NULL ,
                      `executed` BOOLEAN NOT NULL DEFAULT 0,
                      PRIMARY KEY (`id`)  )              
                      ENGINE = InnoDB;");
        
        // Add the foreign key at the end
        $this->addSql("ALTER TABLE courses ADD FOREIGN KEY (initiative_id) REFERENCES initiatives(id)");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
