<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Types\Type;

/**
 * Migration to prepare for course pages. This would involve moving information from offering level
 * to course level. This migration only setups the table for
 *
 */
class Version20130407194255 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // Create the coures_instructors table first
        $this->addSql("CREATE  TABLE IF NOT EXISTS `courses_instructors` (
                      `id` INT NOT NULL AUTO_INCREMENT ,
                      `course_id` INT NOT NULL ,
                      `instructor_id` INT NOT NULL ,
                      PRIMARY KEY (`id`) ,
                      INDEX `courses_instructors.course_id` (`course_id` ASC) ,
                      INDEX `courses_instructors.instructor_id` (`instructor_id` ASC) ,
                      CONSTRAINT `courses_instructors.course_id`
                        FOREIGN KEY (`course_id` )
                        REFERENCES `courses` (`id` )
                        ON DELETE NO ACTION
                        ON UPDATE NO ACTION,
                      CONSTRAINT `courses_instructors.instructor_id`
                        FOREIGN KEY (`instructor_id` )
                        REFERENCES `instructors` (`id` )
                        ON DELETE NO ACTION
                        ON UPDATE NO ACTION)
                      ENGINE = InnoDB;");

        // Adding the following fields to the courses table.
        $this->addSql("ALTER TABLE courses ADD COLUMN video_intro text");
        $this->addSql("ALTER TABLE courses ADD COLUMN url text");
        $this->addSql("ALTER TABLE courses ADD COLUMN `length` int(11)");
        $this->addSql("ALTER TABLE courses ADD COLUMN `status` smallint(6)");
        $this->addSql("ALTER TABLE courses ADD COLUMN `created` timestamp NULL DEFAULT NULL");
        $this->addSql("ALTER TABLE courses ADD COLUMN `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");
        $this->addSql("ALTER TABLE courses ADD COLUMN `short_name` varchar(50)");
        $this->addSql("ALTER TABLE courses ADD COLUMN `description` text");
        $this->addSql("ALTER TABLE courses ADD COLUMN `search_desc` text");
    }


    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
