<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121117223144 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $sql ="
            CREATE TABLE IF NOT EXISTS sphinxsearch(
                 id INT NOT NULL AUTO_INCREMENT ,
                 name VARCHAR(255),
                 instructors TEXT,
                 description TEXT,
                 initiative VARCHAR(50),
                 stream VARCHAR(255),
                 search TEXT,  
                 PRIMARY KEY (id))  
                 ENGINE = InnoDB;";
        $this->addSql($sql);

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql("DROP TABLE sphinxsearch");
    }
}
