<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Migration used to generate the news table
 */
class Version20130617204940 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $sql ="
            CREATE TABLE IF NOT EXISTS news(
                 id INT NOT NULL AUTO_INCREMENT ,
                 title TEXT,
                 url TEXT,
                 created timestamp NULL DEFAULT NULL,
                 modified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                 PRIMARY KEY (id))
                 ENGINE = InnoDB;";
        $this->addSql($sql);

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
