<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Create table to keep track of which courses a user visits. This data
 * would be used to generate recommendations
 */
class Version20130618233140 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
            "CREATE TABLE IF NOT EXISTS user_courses_tracking(
                id INT NOT NULL AUTO_INCREMENT,
                user_identifier VARCHAR(255),
                course_id INT,
                created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id))
                ENGINE = InnoDb;
            )"
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
